import { useEffect, useState } from "react";
import { eventsApi } from "../lib/api";
import type { EventOut } from "../types";
import { CATEGORY_ICONS, CATEGORY_LABELS, formatDateTime } from "../lib/utils";

export default function PublicAdvisoryPage() {
  const [events, setEvents] = useState<EventOut[]>([]);
  const [advisories, setAdvisories] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    eventsApi.list({ status_filter: "active", limit: 20 })
      .then(async (r) => {
        const activeEvents = r.data;
        setEvents(activeEvents);
        const advMap: Record<string, any> = {};
        await Promise.all(
          activeEvents.map(async (ev) => {
            try {
              const detail = await eventsApi.get(ev.id);
              if (detail.data.advisory) advMap[ev.id] = detail.data.advisory;
            } catch { /* skip */ }
          })
        );
        setAdvisories(advMap);
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Public Travel Advisories</h1>
        <p className="text-muted text-sm mt-0.5">
          AI-generated advisories for active events affecting Bengaluru traffic
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center h-40">
          <div className="w-7 h-7 border-2 border-accent border-t-transparent rounded-full animate-spin" />
        </div>
      ) : events.length === 0 ? (
        <div className="glass-card p-12 text-center text-muted">
          <p className="text-4xl mb-3">✅</p>
          <p className="font-semibold">No active traffic advisories</p>
          <p className="text-sm mt-1">Bengaluru roads are running normally right now</p>
        </div>
      ) : (
        <div className="space-y-4">
          {events.map((ev) => {
            const adv = advisories[ev.id];
            return (
              <div key={ev.id} className="glass-card p-5 border-l-4 border-l-amber animate-slide-up">
                <div className="flex items-start gap-3 mb-4">
                  <span className="text-3xl">{CATEGORY_ICONS[ev.category]}</span>
                  <div>
                    <div className="flex items-center gap-2">
                      <h2 className="font-bold text-lg">{ev.event_name}</h2>
                      <span className="badge text-amber bg-amber/10 border-amber/30 text-[10px]">
                        ACTIVE
                      </span>
                    </div>
                    <p className="text-sm text-muted">
                      {CATEGORY_LABELS[ev.category]} · {formatDateTime(ev.start_datetime)} –{" "}
                      {formatDateTime(ev.end_datetime)}
                    </p>
                  </div>
                </div>

                {adv ? (
                  <div className="space-y-3">
                    <div className="bg-amber/5 border border-amber/20 rounded-xl p-4">
                      <p className="text-xs text-amber font-semibold mb-2 uppercase tracking-wide">
                        📱 SMS Alert
                      </p>
                      <p className="text-sm text-white leading-relaxed">{adv.sms_text}</p>
                    </div>
                    <div className="bg-accent/5 border border-accent/20 rounded-xl p-4">
                      <p className="text-xs text-accent font-semibold mb-2 uppercase tracking-wide">
                        🔔 Full Advisory
                      </p>
                      <p className="text-sm text-white leading-relaxed">{adv.notification_text}</p>
                    </div>
                    <div className="bg-surfaceAlt border border-border rounded-xl p-4 font-mono text-sm text-white">
                      <p className="text-xs text-muted mb-2 uppercase tracking-wide">
                        🖥️ Display Board Message
                      </p>
                      {adv.display_board_text}
                    </div>
                  </div>
                ) : (
                  <div className="text-sm text-muted italic">
                    Advisory being generated by AI…
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
